delivery/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
app_name="cart"


urlpatterns = [
   path('addtocart/<n>',views.addtocart,name="addtocart"),
   path('cartview',views.cartview,name="cartview"),
   path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
   path('full_remove/<n>',views.full_remove,name="full_remove"),
   path('orderform',views.orderform,name="orderform"),
   path('orderview', views.orderview, name="orderview"),

   ]

delivery/delivery/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),

]

delivery/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"


urlpatterns = [
   path('',views.search,name="search")
]

delivery/shop/urls.py
from django.urls import path
from shop import views
from django.conf import settings
from django.conf.urls.static import static
app_name="shop"

urlpatterns = [

    path('',views.allcategories,name="allcat"),
    path('allprod/<p>',views.allproducts,name="allprod"),
    path('details/<c>',views.details,name="details"),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

delivery/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price



class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    order_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

class Account(models.Model):
    acctnum=models.IntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return str(self.acctnum)

delivery/search/models.py
from django.db import models

# Create your models here.

delivery/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="category",null=True,blank=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="product",null=True,blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

delivery/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Account,Order
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
                total+=i.quantity*i.product.price
    except:
        pass
    return render(request,'cartview.html',{'c':cart,'total':total})

@login_required
def orderform(request):
    if request.method == "POST":
        a=request.POST['a']
        p = request.POST['p']
        n = request.POST['n']


        u=request.user
        cart=Cart.objects.filter(user=u)

        total=0
        for i in cart:
            total+=i.quantity*i.product.price
        try:
            ac=Account.objects.get(acctnum=n)
            if(ac.amount >= total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                    cart.delete()
                    msg="Your Order placed successfully"
                    return render(request,'orderdetail.html',{'msg':msg})
            else:
                msg="Insufficient Amount.You can't Place order"
                return render(request, 'orderdetail.html', {'msg': msg})


        except:
            pass


    return render(request,'orderform.html')









@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
              cart.quantity+=1
              cart.save()
              p.stock-=1
              p.save()


    except:

        if(p.stock>0):

            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()

    return cartview(request)



@login_required
def cart_remove(request,n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u,product=p)
        if (cart.quantity > 1):
              cart.quantity -= 1
              cart.save()
              p.stock += 1
              p.save()


        else:
            cart.delete()
            p.stock += 1
            p.save()

    except:
        pass
    return cartview(request)



@login_required
def full_remove(request,n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u,product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()


    except:
        pass
    return cartview(request)


@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o,'u':u.username})

delivery/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.
def search(request):
    products=None
    query=""
    if(request.method=="POST"):
        query=request.POST['q']
        print("quest",query)
        if query:

            products=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request,'search.html',{'query':query,'p':products})

delivery/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import login , authenticate,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})

def details(request,c):
    p=Product.objects.get(name=c)
    return render(request,'details.html',{'p':p})

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        fname=request.POST['f']
        lname=request.POST['l']
        e=request.POST['e']

        if(p==cp):
            user=User.objects.create_user(username=u,password=p,first_name=fname,last_name=lname,email=e)
            user.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("Password are not same")
    return render(request,'register.html')
def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            return HttpResponse("Invalid credentials")
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

delivery/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;600;700&family=Poppins:ital,wght@1,100&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>

<header><center>
    <img src="{% static 'images/logo.jpeg' %}" class="mb-2" height="100px" width="100px"></center>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
            {% endfor %}
           </ul>
        </li>
          {% if user.is_authenticated %}


           <li class="nav-item">
          <a class="nav-link"  href="{% url 'shop:logout' %}">Logout</a>
        </li>


          {% if user.is_superuser == False %}


         <li class="nav-item">
          <a class="nav-link fs-5"  href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup class="ms-2">{{count}}</sup></a>
        </li>
          <li class="nav-item">
          <a class="nav-link fs-5"  href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
          {% endif %}

          {% else %}

         <li class="nav-item">
          <a class="nav-link"  href="{% url 'shop:register' %}">Register</a>
        </li>
         <li class="nav-item">
          <a class="nav-link"  href="{% url 'shop:login' %}">Login</a>
        </li>
         {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2"  name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


</header>
{% block content %}



{% endblock %}

<footer>
   <div class="footer">
       <p><b><i class="fa-solid fa-copyright"></i>My Shop  Pvt ltd.All Rights Reserved</b></p>
   </div>

</footer>




</body>
</html>

delivery/templates/cartview.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row fs-5 text-center">
        <h4 class="text-center">Shopping Cart</h4>

        <div class="col-7"><table class="table table-bordered">
            <tr><th colspan="5">Cart Items</th></tr>


              {% for i in c  %}
              <tr><td>
                        <img src="{{i.product.image.url}}" height="200px" width="200px">
              </td>

                  <td>{{i.product.name}}</td>
                  <td><h6>Product ID:{{i.product.id}}</h6>
                      <h6>Unit Price:{{i.product}}</h6>
                      <h6>Quantity:{{i.quantity}}*{{i.product.price}}</h6>
                  </td>
                  <td>Subtotal:{{i.subtotal}}</td>

                  {% if i.product.stock > 0 %}
                  <td><a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-secondary fs-5"></i></a>
                  <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-secondary fs-5"></i></a>
                  <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-secondary fs-5"></i></a>

                  {% else %}

                  <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-secondary fs-5"></i></a>
                  <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-secondary fs-5"></i></a></td>
                       {% endif %}
              </tr>


              {% endfor %}
        </table></div>



        <div class="col-4"><table class="table table-bordered">
            <tr><th colspan="5">Check Out</th></tr>
            <tr><td>TOTAL :{{total}} </td></tr>
        </table>
            <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:relative; right:80px">Place Order</a>
            <a href="{% url 'shop:allcat' %}" class="btn btn-danger" style="position:relative; left:80px">Continue Shopping </a>




        </div>

    </div>
</div>


{% endblock %}

delivery/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
<img src="{% static 'images/banner2.jpg' %}" height="550px" width="100%">
 </div>



<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">Our Collections</h3>
    <p style="text-align:justify;line-height:2">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

</div>

<div class="container-fluid" style="margin-bottom:100px">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" height="200px"  width="100px" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
    <a href="{% url 'shop:allprod' i.name %}" class="btn btn-primary" style="position:relative;left:40%">Product</a>

  </div>
</div>

        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}

delivery/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row">
    <div class="col-sm-4 me-5">
        <img src="{{p.image.url}}" height="400px" width="400px">

    </div>
    <div class="col-sm-6 me-5">
    <h3>{{p.name}}</h3>
        <p class="mt-2 lh-base">{{p.desc}}</p>
        <h2 class="mt-2">{{p.price}}</h2>

        {{p.stock}}

        {% if user.superuser == True %}
        {% if p.stock == 0 %}

        <h2>Out of stock</h2>
        <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD STOCK</a>
        {% else %}

        <h2>Product in stock</h2>
         <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD STOCK</a>
        {% endif %}

        {% else %}

        {% if p.stock == 0 %}
         <h2>Out of stock</h2>
        {% else %}
        <a href="{% url 'cart:addtocart'  p.name %}" class="btn btn-danger mt-2 lh-base ">ADD TO CART</a>
        {% endif %}
        {% endif %}
    </div>
</div>




{% endblock %}

delivery/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block content %}
<center>
<h3>Login</h3>
 <div class="container" style="margin-bottom:100px">
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter the Username">
</div>
    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control"  name="p" placeholder="Enter the Password">
</div>

    <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
</div>
</form>
 </div>
</center>
{% endblock %}

delivery/templates/opendetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
<center>
    <h4 class="text-center text-success">{{msg}}</h4>
    <h4 class="text-center text-danger">Thank You....</h4>
    <h4 class="text-center"><a href="{% url 'shop:allcat' %}">Continue Shopping </a></h4>
</center>
</div>

{% endblock %}

delivery/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block content %}
<center>
    <div class="container" style="  margin-bottom:100px">
<h3>OrderForm</h3>

        <form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control" name="a"  placeholder="Enter the Address">
</div>
    <div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control"  name="p" placeholder="Enter the Phone">
</div>
    <div class="mb-3">
  <label  class="form-label">Account Number</label>
  <input type="number" class="form-control"  name="n" placeholder="Enter the Account Number">
</div>



    <div class="mb-3 mt-3">

  <input type="submit" class="form-control btn btn-secondary">
</div>
</form>

</div>
</center>

{% endblock %}

delivery/templates/orderview.html
 {% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="container">
     <div class="row mt-5">
         <h4 class="text-danger">Name of the customer:{{u}}</h4>
         {% for i in o %}
         <div class="col-sm-4 mt-3"  style="margin-left:100px">
             <img src="{{i.product.image.url}}" height="200px" width="200px">

         </div>
         <div class="col-sm-6 text-center mt-3">
             <b>Product name:{{i.product.name}}</b><br>
             <b>Product price:{{i.product.price}}</b><br>
             <b>Product address:{{i.address}}</b><br>
             <b>Product Phone:{{i.phone}}</b><br>
             <b>Ordered on:{{i.order_date}}</b><br>
             <b class="text-success">Delivery_status:{{i.delivery.status}}</b><br>

         </div>
         {% endfor %}


     </div>
 </div>

{% endblock %}

delivery/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div>
<img src="{{c.image.url}}" height="550px" width="100%">
 </div>



<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="text-align:justify;line-height:2">{{c.desc}}</p>

</div>

<div class="container-fluid" style="margin-bottom:100px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" height="200px"  width="100px" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
      <h5 class="card-title text-center fw-bold">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="position:relative;left:40%">Details</a>
  </div>
</div>

        </div>
        {% endfor %}

    </div>
</div>


{% endblock %}

delivery/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block content %}
<center>
    <div class="container" style="margin-bottom:100px">
<h3>Register</h3>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter the Username">
</div>
    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control"  name="p" placeholder="Enter the Password">
</div>
    <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control"  name="cp" placeholder="Enter the Confirm Password">
</div>

      <div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control"  name="f" placeholder="Enter the First Name">
</div>
      <div class="mb-3">
  <label  class="form-label">last Name</label>
  <input type="text" class="form-control"  name="l" placeholder="Enter the Last Name">
</div>
      <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="text" class="form-control"  name="e" placeholder="Enter the Email">
</div>


    <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
</div>
</form>
        </div>
</center>

{% endblock %}

delivery/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block content %}
<center>
<div>
<h3>You have searched for {{query}}</h3>
 </div></center>



<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="text-align:justify;line-height:2">{{c.desc}}</p>

</div>


<div class="container-fluid" style="margin-bottom:100px">
    <div class="row">
        {% if p %}
        {% for i in p %}
        <div class="col-sm-4 mb-5">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="200px"  width="100px" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
      <h5 class="card-title text-center fw-bold">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="position:relative;left:40%">Details</a>
  </div>
</div>

            {% endfor %}
            {% else %}
            <h4 class="text-center">No Results Found</h4>
            {% endif %}

        </div>
    </div>
{% endblock %}